default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  port: 3306

development:
  <<: *default
  database: bob_development
  username: root
  password: root

test:
  <<: *default
  database: bob_test
  username: root
  password: root

production:
  <<: *default
  database: bob_production

